name: battery_example
description: Demonstrates how to use the battery_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  battery_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test: ^0.8.0
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
