name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using
  the ACTION_SEND intent on Android and UIActivityViewController on iOS.
homepage: https://github.com/fluttercommunity/share_plus
# 0.6.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.6.5

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.share
        pluginClass: SharePlugin
      ios:
        pluginClass: FLTSharePlugin
      linux:
        default_package: share_plus_linux

dependencies:
  meta: ^1.0.5
  mime: ^0.9.7
  flutter:
    sdk: flutter
  share_plus_platform_interface:
    path: ../share_plus_platform_interface/
  share_plus_linux:
    path: ../share_plus_linux

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
