name: connectivity_plus_macos
description: macOS implementation of the connectivity_plus plugin.
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.1.0+6
homepage: https://github.com/fluttercommunity/connectivity_plus_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ConnectivityPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  connectivity_plus_platform_interface:
    path: ../connectivity_plus_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
