name: battery_plus_for_web
description: An implementation for the web platform of the Flutter `battery_plus` plugin.
version: 1.0.0
homepage: https://github.com/fluttercommunity/battery_plus/battery_plus_for_web/experimental_battery_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BatteryPlusPlugin
        fileName: battery_plus_for_web.dart

dependencies:
  battery_plus_platform_interface:
    path: ../battery_plus_platform_interface
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.0
  mockito: ^4.1.2

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'
