name: all_plugins

github_checkout: &github_checkout
  name: "Git Checkout"
  uses: actions/checkout@v2
  with:
    fetch-depth: 0

install_flutter: &install_flutter
  name: "Install Flutter"
  uses: subosito/flutter-action@v1
  with:
    flutter-version: "2.2.1"

bootstrap_tools: &bootstrap_tools
  name: "Bootstrap Melos/Tools"
  uses: ./.github/actions/melos

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - *github_checkout
      - *install_flutter
      - name: "Analyze"
        uses: ./.github/actions/analyze

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - *github_checkout
      - *install_flutter
      - name: "Format"
        uses: ./.github/actions/format

  build_examples_dart:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - *github_checkout
      - *install_flutter
      - *bootstrap_tools
      - name: "Build Example Snapshots"
        run: |
          melos run build:examples:bundle

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - *github_checkout
      - *install_flutter
      - *bootstrap_tools
      - name: "Flutter Test"
        run: |
          melos run test
        if: matrix.os != 'ubuntu-latest'
      - name: "Collect Coverage"
        run: |
          melos run coverage
        if: matrix.os == 'ubuntu-latest'
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: packages/*/coverage/lcov.info
        if: matrix.os == 'ubuntu-latest'

  integration_tests:
    if: ${{ false }} # currently broken, see issue 220
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - *github_checkout
      - *install_flutter
      - *bootstrap_tools
      - name: "Setup Linux"
        run: |
          sudo apt update
          sudo apt install -y cmake dbus libblkid-dev libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb clang-format
          sudo apt install -y network-manager upower
        if: matrix.os == 'ubuntu-latest'
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Flutter Integration Test"
        run: |
          melos run test:e2e:linux
        if: matrix.os == 'ubuntu-latest'
